[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
# Improves performance while sacrificing compatibility
{% if native != true %}#{% endif %}"-Ctarget-cpu=native",
#Pick one of the two following options, prefer mold if available
{% if linker != "LLD" %}#{% endif %}"-Clink-arg=-fuse-ld=lld",
{% if linker != "Mold" %}#{% endif %}"-Clink-arg=-fuse-ld=mold",

# Nightly{% if nightly %}
    "-Zshare-generics=y",
    "-Zthreads=0",
{% else %}
    #"-Zshare-generics=y",
    #"-Zthreads=0",
{% endif %}]


[target.x86_64-apple-darwin]
rustflags = [
# Improves performance while sacrificing compatibility
{% if native != true %}#{% endif %}"-Ctarget-cpu=native",

# Nightly{% if nightly %}
    "-Zshare-generics=y",
    "-Zthreads=0",
{% else %}
    #"-Zshare-generics=y",
    #"-Zthreads=0",
{% endif %}]
[target.aarch64-apple-darwin]
rustflags = [
# Improves performance while sacrificing compatibility
{% if native != true %}#{% endif %}"-Ctarget-cpu=native",

# Nightly{% if nightly %}
    "-Zshare-generics=y",
    "-Zthreads=0",
{% else %}
    #"-Zshare-generics=y",
    #"-Zthreads=0",
{% endif %}]


[target.x86_64-pc-windows-msvc]
rustflags = [
# Improves performance while sacrificing compatibility
{% if native != true %}#{% endif %}"-Ctarget-cpu=native",
{% if linker != "LLD" %}#{% endif %}"-Clink-arg=-fuse-ld=lld",

# Nightly{% if nightly %}
    "-Zshare-generics=y",
    "-Zthreads=0",
{% else %}
    #"-Zshare-generics=y",
    #"-Zthreads=0",
{% endif %}]
